import { Spotlight } from "../ui/Spotlight";

export function SpotlightPrev() {
  return (
    <div className="h-[40rem] w-full flex md:items-center md:justify-center bg-black/[0.96] antialiased bg-grid-white/[0.02] relative overflow-hidden">
      <Spotlight
        className="-top-40 left-0 md:left-60 md:-top-20"
        fill="white"
      />
      <div className="p-4 max-w-7xl  mx-auto relative z-10  w-full pt-20 md:pt-0">
        <h1 className="text-4xl md:text-7xl font-bold text-center bg-clip-text text-transparent bg-gradient-to-b from-neutral-50 to-neutral-400 bg-opacity-50">
          Welcome to <br /> Your WiJungle's Security Dashboard.
        </h1>
        <p className="mt-12 font-normal text-xl text-neutral-50  max-w-lg text-center mx-auto">
          This dashboard provides you with a comprehensive overview of the
          security alerts generated by your system. The visualizations below
          offer insights into various aspects of the alerts, helping you
          understand and analyze potential security threats.<br/> <span className="text-2xl">Scroll Down to See amazing Charts.</span>
        </p>
      </div>
    </div>
  );
}
